### ISSUE TITLE
not wroking

### ISSUE THREAD

**Issue by benthebear93** [Interactics/install_ROS_Melodic#1]
as i follow this command lines, it end up giving me a permission error when i catkin_make.
i ran catkin_make in this path (~/catkin_ws/src).

something weird about this shell is catkin_ws folder icon has a lock icon with it,
typically meaning permission error. 

so when i ran catkin_make. it returns permission error.
and "sudo catkin_make" wouldn't work. Because catkin_make with sudo is totally different  thing.

hope you take a time to fix this 

thx.

**Comment by Interactics** [comment]
There was an error in running `./installROSMelodic.sh`.
I changed installation code from `sudo bash ./installROSMelodic.sh` to `./installROSMelodic.sh`
now, It will work well.
